### ISSUE TITLE
pkg_resources.get_distribution('psycopg2') fails with DistributionNotFound

### ISSUE THREAD

**Issue by radix** [jetbridge/psycopg2-lambda-layer#6]
Using the python 3.6 layer, I am trying to use the [sqlalchemy-redshift](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift) package.

This package has the following code in its `__init__` module:

```python
try:
    import psycopg2  # noqa: F401
    if get_distribution('psycopg2').parsed_version < parse_version('2.5'):
        raise ImportError('Minimum required version for psycopg2 is 2.5')
```

This code is successfully importing `psycopg2`, but is then failing with the following error:

```
Traceback (most recent call last):
  File "/var/task/app.py", line 14, in <module>
    import sqlalchemy_redshift # just testing
  File "/var/task/sqlalchemy_redshift/__init__.py", line 5, in <module>
    if get_distribution('psycopg2').parsed_version < parse_version('2.5'):
  File "/var/lang/lib/python3.6/site-packages/pkg_resources/__init__.py", line 479, in get_distribution
    dist = get_provider(dist)
  File "/var/lang/lib/python3.6/site-packages/pkg_resources/__init__.py", line 355, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/var/lang/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/var/lang/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psycopg2' distribution was not found and is required by the application
```

This implies to me that *something* about the way the psycopg2 is installed isn't meeting all the requirements of some of the "standard" packaging tools in the Python world, but I am not 100% sure about all the details of this.

**Comment by revmischa** [comment]
Dunno what to do about this and it's hella old
